# Generated by Django 6.1 on 2026-10-01 18:33

import django.db.models.deletion
import urlapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=urlapp.models.gerar_codigo_unico, max_length=10, unique=True)),
                ('url_destination', models.URLField(max_length=2048)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('url_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'tb_link',
            },
        ),
    ]
